### ISSUE TITLE
Create AnimatorListener ktx extension for us to omit no-op implementations

### ISSUE THREAD

**Issue by Iannnr** [boswelja/Ephemeris#41]
I wonder if there exists an AnimatorListener which acts like the core-ktx 
```
public inline fun TextView.doOnTextChanged(
    crossinline action: (
        text: CharSequence?,
        start: Int,
        before: Int,
        count: Int
    ) -> Unit
): TextWatcher = addTextChangedListener(onTextChanged = action)
```
So you only need to implement doOnAnimationEnd and doOnAnimationCancel so we can omit the no-ops 🤔

_Originally posted by @Iannnr in https://github.com/boswelja/Ephemeris/pull/40#discussion_r840462493_

**Comment by boswelja** [comment]
We can probably copy-paste the androidx-core-ktx implementation for this tbh

**Comment by boswelja** [comment]
Apparently GitHub didn't auto-close this :(
