### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by EdricChan03** [boswelja/Ephemeris#71]
**Is your feature request related to a problem? Please describe.**
It would be nice to see a brief summary of all the public-facing APIs the library has to offer

**Describe the solution you'd like**
[Dokka](https://github.com/Kotlin/dokka) can be used to auto-generate such docs.

**Describe alternatives you've considered**
N/A

**Other**
I'm currently working on a draft implementation of Dokka support which can be found in the [feat/dokka branch](https://github.com/EdricChan03/Ephemeris/tree/feat/dokka) (of my own fork)

**Comment by boswelja** [comment]
What does a typical deployment look like? Is is a separate branch in the same repo?
