### ISSUE TITLE
Flutter Support

### ISSUE THREAD

**Issue by JustINCodingUK** [boswelja/Ephemeris#88]
Currently, most of the platforms are supported for core. Adding flutter support would extend the library's UI support for many platforms, with a single Dart codebase.

**Comment by boswelja** [comment]
You have a flutter label now, no pressure 😆

**Comment by JustINCodingUK** [comment]
Flutter's MethodChannel APIs only support primitive and basic types yet, so it's not possible to integrate core without porting it to dart.
