### ISSUE TITLE
Android XML Views UI

### ISSUE THREAD

**Issue by boswelja** [boswelja/Ephemeris#9]
Tracking progress of XML view-based UI

- [x] Create module
- [x] Load data from CalendarPageLoader
- [x] Expose currently displayed month
- [x] Allow external control over the page number (scroll to, etc)
- [x] Animate CalendarPageLoader changes
- [ ] #27

**Comment by Iannnr** [comment]
does #8 solve ` Support FocusMode` or does more work need to be done?

**Comment by boswelja** [comment]
As long as it's supported in a way you're happy with
